### ISSUE TITLE
能上V3吗

### ISSUE THREAD

**Issue by KuroshioDev** [Lumie-fx/ayaka-plugin#2]
****

**Comment by Lumie-fx** [comment]
yunzai3.0的issue一直反馈有问题，我前两天试过miao放进去也有点问题，回头我再看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月4日(周四) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lumie-fx/ayaka-plugin] 能上V3吗 (Issue #2)

**Comment by KuroshioDev** [comment]
我已经改好了。怎么能联系到你

**Comment by Lumie-fx** [comment]
***@***.***
微信fxwill1123
大半夜的还不睡觉。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月7日(周日) 凌晨3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lumie-fx/ayaka-plugin] 能上V3吗 (Issue #2)




 
我已经改好了。怎么能联系到你
