### ISSUE TITLE
关于圣遗物强化

### ISSUE THREAD

**Issue by hxwd94666** [Lumie-fx/ayaka-plugin#3]
大佬您好，请问圣遗物强化能一键强化到20的代码吗？如果有，请您告诉我一下，如果没有，您方便添加一下吗？谢谢！

**Comment by Lumie-fx** [comment]
在整个大活原来的计划都给冲掉了，不过这个可以有，明天有空就给加上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lumie-fx/ayaka-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月17日(星期三) 凌晨0:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lumie-fx/ayaka-plugin] 关于圣遗物强化 (Issue #3)





 
大佬您好，请问圣遗物强化能一键强化到20的代码吗？如果有，请您告诉我一下，如果没有，您方便添加一下吗？谢谢！

**Comment by Lumie-fx** [comment]
> 大佬您好，请问圣遗物强化能一键强化到20的代码吗？如果有，请您告诉我一下，如果没有，您方便添加一下吗？谢谢！

指令“强化20”
