### ISSUE TITLE
关于抽须弥新圣遗物

### ISSUE THREAD

**Issue by ziiqq** [Lumie-fx/ayaka-plugin#5]
话说抽圣遗物的功能，还会继续加须弥的新圣遗物套装嘛？

**Comment by Lumie-fx** [comment]
master分支3.0部分应该是支持的吧，现在想在那边把养成做起来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月20日(周二) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lumi-fx/ayaka-plugin] 关于抽须弥新圣遗物 (Issue #5)




 
话说抽圣遗物的功能，还会继续加须弥的新圣遗物套装嘛？

**Comment by ziiqq** [comment]
收到收到 我没仔细看 谢谢谢谢
