### ISSUE TITLE
更新喵喵插件重启后再次出现报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Lumie-fx/ayaka-plugin#7]
如图 望适配
![Screenshot_20220929-131852_Microsoft_远程桌面.png](https://user-images.githubusercontent.com/86163024/192955448-18422898-f291-455d-8fcb-b8c183a4a64b.png)

**Comment by YuYue-Amatsuki** [comment]
补充：喵喵插件为今天更新的新版本

**Comment by Lumie-fx** [comment]
bug，昨天玩3.1玩high了没测这部分功能，不过这个功能暂时只是在测试，不会有啥影响，晚点回去修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月29日(周四) 下午2:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Lumie-fx/ayaka-plugin] 更新喵喵插件重启后再次出现报错 (Issue #7)




 
补充：喵喵插件为今天更新的新版本

**Comment by Lumie-fx** [comment]
好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lumie-fx/ayaka-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 下午2:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Lumie-fx/ayaka-plugin] 更新喵喵插件重启后再次出现报错 (Issue #7)





 
补充：喵喵插件为今天更新的新版本
